server:
  port: 8100
  servlet:
    context-path: "/cwi-turing"

spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    #antonio
    url: jdbc:oracle:thin:@192.168.56.106:1521/XEPDB1

    #larissa
    #url: jdbc:oracle:thin:@192.168.248.3:1521/XEPDB1

    #vanessa
    #url: jdbc:oracle:thin:@192.168.56.101:1521/XE
    #url: jdbc:oracle:thin:@192.168.64.3:1521/XEPDB1

    username: CWITURING
    password: CWITURING
    driver-class-name: oracle.jdbc.OracleDriver
