server:
  port: 8100
  servlet:
    context-path: "/cwi-turing"

spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@192.168.56.106:1521/XEPDB1
    username: CWITURING
    password: CWITURING
    driver-class-name: oracle.jdbc.OracleDriver
