server:
  port: 8100
  servlet:
    context-path: "/cwi-turing"

spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@10.99.220.139:1521/XEPDB1

    username: CRECWITURING
    password: CRECWITURING
    driver-class-name: oracle.jdbc.OracleDriver
