server:
  port: 8100
  servlet:
    context-path: "/cwi-turing"

security:
  oauth2:
    resource:
      user-info-uri: https://auth-homolog.cwi.com.br/connect/userinfo
      jwt:
        secret: "cwi-turing"

spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tcc.turing@gmail.com
    password: tcc12345turing
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    test-connection: true

  datasource:
    url: jdbc:oracle:thin:@10.99.220.141:1521/odev12c
    username: CRECWITURING
    password: CRECWITURING

    driver-class-name: oracle.jdbc.OracleDriver
