export { Informacoes } from './blocoInformacoesProva'
export { BlocoQuestaoDissertativa } from './blocoDissertativa'
export { BlocoQuestaoMultiplaEscolha } from './blocoMultiplaEscolha'
export { BlocoQuestaoTecnica } from './blocoTecnica'
export { BlocoComentario } from './blocoComentario'
export { BlocoNota } from './blocoNota'
export { MyDocument } from './pdf'
export { styles } from './style'
