------------------------------------------------------------------------------------------------------------------------------
------------------ Script de Criação das Foreign Key do Banco - CWI Turing - CRESCER 2019 ------------------------------------
------------------------------------------------------------------------------------------------------------------------------

/******************************* FOREIGN KEY *******************************/
--ALTERNATIVAS DA QUESTAO DE MULTIPLA ESCOLHA
ALTER TABLE ALTERNATIVAS_MULTIPLA_ESCOLHA
ADD CONSTRAINT FK_IDQUEST_ALTERNATIVA
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_MULTIPLA_ESCOLHA (ID);

/******************************* FOREIGN KEY DAS TABELAS DE LIGAÇÃO *******************************/
--QUESTAO_TECNICA -> PROVAS
ALTER TABLE TECNICA_PROVAS
ADD CONSTRAINT FK_IDPROVA_TECNICA_PROVAS
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

ALTER TABLE TECNICA_PROVAS
ADD CONSTRAINT FK_IDQUESTAO_TECNICA_PROVAS
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_TECNICA (ID);

--QUESTAO_DISSERTATIVA -> PROVAS
ALTER TABLE DISSERTATIVA_PROVAS
ADD CONSTRAINT FK_IDPROVA_DISSERTATIVA_PROVAS
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

ALTER TABLE DISSERTATIVA_PROVAS
ADD CONSTRAINT FK_IDQUEST_DISSERTATIVA_PROVAS
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_DISSERTATIVA (ID);

--QUESTAO_MULTIPLA_ESCOLHA -> PROVAS
ALTER TABLE MULTIPLA_ESCOLHA_PROVAS
ADD CONSTRAINT FK_IDPROVA_MULT_ESCOLHA_PROVAS
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

ALTER TABLE MULTIPLA_ESCOLHA_PROVAS
ADD CONSTRAINT FK_IDQUEST_MULT_ESCOLHA_PROVAS
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_MULTIPLA_ESCOLHA (ID);


/******************************* FOREIGN KEY DAS TABELAS DE RESPOSTAS DA PROVA *******************************/
--RESPOSTAS -> QUESTÕES DISSERTATIVAS
ALTER TABLE RESPOSTAS_DISSERTATIVAS_PROVAS
ADD CONSTRAINT FK_IDQUEST_RESP_DISSERTATIVAS
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_DISSERTATIVA (ID);

ALTER TABLE RESPOSTAS_DISSERTATIVAS_PROVAS
ADD CONSTRAINT FK_IDPROVA_RESP_DISSERTATIVAS
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

--RESPOSTAS -> QUESTÕES TECNICAS
ALTER TABLE RESPOSTAS_TECNICAS_PROVAS
ADD CONSTRAINT FK_IDQUESTAO_RESP_TECNICAS
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_TECNICA (ID);

ALTER TABLE RESPOSTAS_TECNICAS_PROVAS
ADD CONSTRAINT FK_IDPROVA_RESP_TECNICAS
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

--TABELA RESPOSTAS -> QUESTÕES MULTIPLAS ESCOLHAS
ALTER TABLE RESPOSTAS_MULT_ESCOLHAS_PROVAS
ADD CONSTRAINT FK_IDALTERNATIVA_MULT_ESCOLHAS
FOREIGN KEY (ID_ALTERNATIVA)
REFERENCES ALTERNATIVAS_MULTIPLA_ESCOLHA (ID);

ALTER TABLE RESPOSTAS_MULT_ESCOLHAS_PROVAS
ADD CONSTRAINT FK_IDQUESTAO_RESP_MULT
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_MULTIPLA_ESCOLHA (ID);

ALTER TABLE RESPOSTAS_MULT_ESCOLHAS_PROVAS
ADD CONSTRAINT FK_IDPROVA_RESP_MULT_ESC
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);
