------------------------------------------------------------------------------------------------------------------------------
------------------------- Script de Criação do Banco - CWI Turing - CRESCER 2019 ---------------------------------------------
------------------------------------------------------------------------------------------------------------------------------

/* CRIAÇÃO DA TABLESPACE E DO USUARIO */
CREATE TABLESPACE CWITURING
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/CWITURING.DBF'
SIZE 100M 
AUTOEXTEND ON NEXT 100M 
MAXSIZE 1024M;

CREATE USER CWITURING IDENTIFIED BY CWITURING DEFAULT TABLESPACE CWITURING;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO CWITURING;

ALTER USER CWITURING QUOTA UNLIMITED ON CWITURING;

/* TABELAS */
--TABELA USUARIO
CREATE TABLE USUARIO(
  ID NUMBER NOT NULL PRIMARY KEY --PK
);
CREATE SEQUENCE "CWITURING"."SEQ_USUARIO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

--TABELA QUESTÃO TÉCNICA
CREATE TABLE QUESTAO_TECNICA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL NUMBER(1) NOT NULL,
  ID_CRIADOR NUMBER NOT NULL --FK USUARIO
);
CREATE SEQUENCE "CWITURING"."SEQ_QUESTAO_TECNICA" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE QUESTAO_TECNICA
ADD CONSTRAINT FK_IDUSUARIO_QUESTAO_TECNICA
FOREIGN KEY (ID_CRIADOR)
REFERENCES USUARIO (ID);

--TABELA QUESTÃO DISSERTATIVA
CREATE TABLE QUESTAO_DISSERTATIVA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL VARCHAR(8) NOT NULL,
  ID_CRIADOR NUMBER NOT NULL --FK USUARIO
);
CREATE SEQUENCE "CWITURING"."SEQ_QUESTAO_DISSERTATIVA" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE QUESTAO_DISSERTATIVA
ADD CONSTRAINT FK_IDUSUARIO_QUESTAO_DISSERTATIVA
FOREIGN KEY (ID_CRIADOR)
REFERENCES USUARIO (ID);

--TABELA QUESTÃO DISSERTATIVA
CREATE TABLE QUESTAO_MULTIPLA_ESCOLHA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL NUMBER(1) NOT NULL,
  ID_CRIADOR NUMBER NOT NULL --FK USUARIO
);
CREATE SEQUENCE "CWITURING"."SEQ_QUESTAO_MULTIPLA_ESCOLHA" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE QUESTAO_MULTIPLA_ESCOLHA
ADD CONSTRAINT FK_IDUSUARIO_QUESTAO_MULT_ESCOLHA
FOREIGN KEY (ID_CRIADOR)
REFERENCES USUARIO (ID);

--TABELA ALTERNATIVAS DA QUESTAO DE MULTIPLA ESCOLHA
CREATE TABLE ALTERNATIVAS_MULTIPLA_ESCOLHA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  RESPOSTA VARCHAR(300) NOT NULL,
  CORRETA CHAR(1) NOT NULL,
  ID_QUESTAO NUMBER NOT NULL --FK QUESTAO
);
CREATE SEQUENCE "CWITURING"."SEQ_ALTERNATIVAS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE ALTERNATIVAS_MULTIPLA_ESCOLHA
ADD CONSTRAINT FK_IDQUESTAO_MULT_ESCOLHA
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO_MULTIPLA_ESCOLHA (ID);

--TABELA PROVAS
CREATE TABLE PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  DURACAO NUMBER NOT NULL, 
  TEMPO_INICIO NUMBER NOT NULL,
  STATUS CHAR(1) NOT NULL,
  ID_CRIADOR NUMBER NOT NULL --FK USUARIO
);
CREATE SEQUENCE "CWITURING"."SEQ_PROVAS" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE PROVAS
ADD CONSTRAINT FK_IDUSUARIO_PROVAS
FOREIGN KEY (ID_CRIADOR)
REFERENCES USUARIO (ID);

--TABELA QUESTAO_PROVA
CREATE TABLE QUESTAO_PROVA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

ALTER TABLE QUESTAO_PROVA
ADD CONSTRAINT FK_IDPROVA
FOREIGN KEY (ID_PROVA)
REFERENCES PROVAS (ID);

ALTER TABLE QUESTAO_PROVA
ADD CONSTRAINT FK_IDQUESTAO
FOREIGN KEY (ID_QUESTAO)
REFERENCES QUESTAO (ID);





