------------------------------------------------------------------------------------------------------------------------------
----------------------- Script de Criação das Sequences do Banco - CWI Turing - CRESCER 2019 ---------------------------------
------------------------------------------------------------------------------------------------------------------------------

/******************************* SEQUENCES *******************************/
--USUARIO
CREATE SEQUENCE SEQ_USUARIO
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--QUESTÃO TÉCNICA
CREATE SEQUENCE SEQ_QUESTAO_TECNICA
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--QUESTÃO DISSERTATIVA
CREATE SEQUENCE SEQ_QUESTAO_DISSERTATIVA
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--QUESTÃO MULTIPLA ESCOLHA
CREATE SEQUENCE SEQ_QUESTAO_MULTIPLA_ESCOLHA
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--ALTERNATIVAS DA QUESTAO DE MULTIPLA ESCOLHA
CREATE SEQUENCE SEQ_ALTERNATIVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--PROVAS
CREATE SEQUENCE SEQ_PROVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

/******************************* SEQUENCE DAS TABELAS DE LIGAÇÃO *******************************/
--QUESTAO_TECNICA -> PROVAS
CREATE SEQUENCE SEQ_TECNICA_PROVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--QUESTAO_DISSERTATIVA -> PROVAS
CREATE SEQUENCE SEQ_DISSERTATIVA_PROVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--QUESTAO_MULTIPLA_ESCOLHA -> PROVAS
CREATE SEQUENCE SEQ_MULTIPLA_ESCOLHA_PROVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

/******************************* SEQUENCES DAS TABELAS DE RESPOSTAS DA PROVA *******************************/
--RESPOSTAS -> QUESTÕES DISSERTATIVAS
CREATE SEQUENCE SEQ_RESPOSTAS_DISSERTATIVAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--RESPOSTAS -> QUESTÕES TECNICAS
CREATE SEQUENCE SEQ_RESPOSTAS_TECNICAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;

--RESPOSTAS -> QUESTÕES MULTIPLAS ESCOLHAS
CREATE SEQUENCE SEQ_RESPOSTAS_MULT_ESCOLHAS
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  CACHE 10000;
