------------------------------------------------------------------------------------------------------------------------------
------------------ Script de Criação das Tabelas do Banco - CWI Turing - CRESCER 2019 ----------------------------------------
------------------------------------------------------------------------------------------------------------------------------

/******************************* TABELAS *******************************/
--TABELA USUARIO
CREATE TABLE USUARIO(
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  EMAIL VARCHAR(50) NOT NULL,
  PERFIL VARCHAR(13) NOT NULL
);

--TABELA QUESTÃO TÉCNICA
CREATE TABLE QUESTAO_TECNICA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL VARCHAR(8) NOT NULL,
  VEZES_USADA INT DEFAULT 0,
  RESPOSTA_BASE VARCHAR2(500) NOT NULL,
  TESTE_BASE VARCHAR2(500) NOT NULL
);

--TABELA QUESTÃO DISSERTATIVA
CREATE TABLE QUESTAO_DISSERTATIVA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL VARCHAR(8) NOT NULL,
  VEZES_USADA INT DEFAULT 0
);

--TABELA QUESTÃO MULTIPLA ESCOLHA
CREATE TABLE QUESTAO_MULTIPLA_ESCOLHA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  QUESTAO VARCHAR2(500) NOT NULL,
  ESPECIFICIDADE VARCHAR(12) NOT NULL,
  NIVEL VARCHAR2(8) NOT NULL,
  VEZES_USADA INT DEFAULT 0
);

--TABELA ALTERNATIVAS DA QUESTAO DE MULTIPLA ESCOLHA
CREATE TABLE ALTERNATIVAS_MULTIPLA_ESCOLHA (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  RESPOSTA VARCHAR(300) NOT NULL,
  CORRETA CHAR(1) NOT NULL,
  ID_QUESTAO NUMBER NOT NULL --FK QUESTAO
);

--TABELA PROVAS
CREATE TABLE PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  DATA_CRIACAO DATE NOT NULL,
  NOME_CANDIDATO VARCHAR2(100),
  EMAIL_CANDIDATO VARCHAR2(50) NOT NULL,
  DURACAO NUMBER NOT NULL, 
  TEMPO_INICIO NUMBER NOT NULL,
  DATA_INICIO DATE,
  STATUS VARCHAR2(30) NOT NULL,
  NOTA NUMBER(10, 2) DEFAULT 0
);

/******************************* TABELAS DE LIGAÇÃO *******************************/
--TABELA QUESTAO_TECNICA -> PROVAS
CREATE TABLE TECNICA_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

--TABELA QUESTAO_DISSERTATIVA -> PROVAS
CREATE TABLE DISSERTATIVA_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

--TABELA QUESTAO_MULTIPLA_ESCOLHA -> PROVAS
CREATE TABLE MULTIPLA_ESCOLHA_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

/******************************* TABELAS DE RESPOSTAS DA PROVA *******************************/
--TABELA RESPOSTAS -> QUESTÕES DISSERTATIVAS
CREATE TABLE RESPOSTAS_DISSERTATIVAS_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  RESPOSTA VARCHAR(500) NOT NULL,
  COMENTARIO VARCHAR2(500),
  NOTA NUMBER(10) NOT NULL,
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

--TABELA RESPOSTAS -> QUESTÕES TECNICAS
CREATE TABLE RESPOSTAS_TECNICAS_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  RESPOSTA VARCHAR(500) NOT NULL,
  COMENTARIO VARCHAR2(500),
  NOTA NUMBER(10) NOT NULL,
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

--TABELA RESPOSTAS -> QUESTÕES MULTIPLAS ESCOLHAS
CREATE TABLE RESPOSTAS_MULT_ESCOLHAS_PROVAS (
  ID NUMBER NOT NULL PRIMARY KEY, --PK
  ID_ALTERNATIVA NUMBER NOT NULL, --FK
  ID_QUESTAO NUMBER NOT NULL, --FK
  ID_PROVA NUMBER NOT NULL --FK
);

